#!/usr/bin/env node
// Inline the app's real stylesheets into a mockup, so the file renders the
// SHIPPED css anywhere it is opened — including a phone reaching it through a
// share sheet or a `content://` provider, where a relative <link> to
// `../frontend/src/…` cannot resolve.
//
// Why this exists (CLAUDE.md rule 8 / ADR-0096): a mockup that hand-copies the
// token values drifts from the app the day either one changes — which is how
// `map-embedded-v1.html`'s first pass ended up drawing a filled amber pill for
// a tag the app renders as amber-deep TEXT. Copying mechanically from source
// keeps "the app's real css" true and portable at the same time, and any app
// change that lands here shows up in `git diff`.
//
// Usage:  node mockups/tools/inline-app-css.mjs <mockup.html> [...more.html]
//
// Contract, per file: a manifest comment naming the stylesheets in the app's
// own import order, followed by the generated block it fills.
//
//   <!-- APP-CSS: styles/tokens.css, App.css, screens/map.css -->
//   <style data-app-css>…generated…</style>
//
// Paths are relative to `frontend/src/`. Re-running is idempotent, so it is
// safe in a pre-commit hook or by hand. A mockup with no manifest is skipped,
// not an error — most mockups are deliberately standalone.

import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const REPO = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const SRC = path.join(REPO, 'frontend/src');

const MANIFEST = /<!--\s*APP-CSS:\s*([^>]+?)\s*-->/;
const BLOCK = /(<style data-app-css>)[\s\S]*?(<\/style>)/;

async function inline(file) {
  const html = await readFile(file, 'utf8');

  const manifest = html.match(MANIFEST);
  if (!manifest) return `${path.basename(file)}: no APP-CSS manifest, skipped`;

  // Search for the block only AFTER the manifest. A mockup that documents this
  // contract in a comment mentions the tag name in prose, and matching that
  // first swallowed the real block (and the manifest with it) on the very first
  // run — the generator ate its own documentation.
  const from = manifest.index + manifest[0].length;
  const head = html.slice(0, from);
  const tail = html.slice(from);
  if (!BLOCK.test(tail)) {
    throw new Error(`${file}: has an APP-CSS manifest but no generated block after it`);
  }

  const sheets = manifest[1]
    .split(',')
    .map((s) => s.trim())
    .filter(Boolean);

  const parts = [];
  for (const sheet of sheets) {
    const from = path.join(SRC, sheet);
    if (!from.startsWith(SRC + path.sep)) throw new Error(`${file}: ${sheet} escapes frontend/src`);
    const css = await readFile(from, 'utf8');
    parts.push(`/* ═══ ${sheet} — generated, do not edit here ═══ */\n${css.trim()}`);
  }

  // A generated banner, so nobody edits the block by hand and loses it on the
  // next run. Kept inside the <style> so it survives Prettier.
  const banner =
    '/* GENERATED by mockups/tools/inline-app-css.mjs from the manifest above.\n' +
    '   Do not edit below this line — change the app css, then re-run the tool. */';
  const body = `\n${banner}\n${parts.join('\n\n')}\n`;

  // Replace via a function so `$&`/`$1` sequences inside the css are literal.
  const next = head + tail.replace(BLOCK, (_m, open, close) => open + body + close);
  if (next === html) return `${path.basename(file)}: already current`;
  await writeFile(file, next);
  const kb = Math.round(body.length / 1024);
  return `${path.basename(file)}: inlined ${sheets.length} stylesheets (${kb} kB)`;
}

const files = process.argv.slice(2);
if (files.length === 0) {
  console.error('usage: node mockups/tools/inline-app-css.mjs <mockup.html> [...]');
  process.exit(1);
}
for (const f of files) console.log(await inline(path.resolve(f)));
