// **The CLDR names and symbols, snapshotted** — the fallback for an engine that
// does not carry them (ADR-0180 §6's amendment).
//
// §6 chose `Intl` over a shipped dataset and that choice stands: the runtime is
// still asked FIRST, and on a full-ICU build every value here is exactly what it
// answers. What this adds is a floor, because a real phone turned out to ship
// without ISK at all — and an engine missing a currency does not merely omit it
// from `supportedValuesOf`, it renders that currency's NAME as the bare code. So
// the row came back once the list was unioned, and then dropped out of a `כתר`
// search anyway, because it no longer had a name to match.
//
// Patching that per currency is what the first fix did, and it does not scale:
// the problem is not ISK, it is ANY currency an engine trims. This table is the
// general answer — every currency keeps its Hebrew name, its English name and
// both symbols on every engine, so the picker reads the same and searches the
// same everywhere.
//
// **Generated, not hand-written** — see `scripts/gen-currency-names.mjs`. Every
// value is written out in full: a currency with no distinct symbol carries its
// own CODE in that slot, exactly as `Intl` answers, rather than an empty string
// standing for "same as the code". That convention saved ~1.5 KB and cost a rule
// every future reader would have to know, whose failure mode is a blank name on
// screen. A stale entry is harmless by construction: it is consulted only when
// the runtime has nothing to say, and the runtime wins whenever it does.

/** `code → [Hebrew name, English name, narrow symbol, wide symbol]`. */
export const CURRENCY_NAMES: Record<string, readonly [string, string, string, string]> = {
  AED: ['דירהם של איחוד הנסיכויות הערביות', 'UAE dirhams', 'AED', 'AED'],
  AFN: ['אפגני אפגני', 'Afghan Afghani', '؋', 'AFN'],
  ALL: ['לק אלבני', 'Albanian lek', 'ALL', 'ALL'],
  AMD: ['דראם ארמני', 'Armenian drams', '֏', 'AMD'],
  ANG: ['גילדר של האנטילים ההולנדיים', 'Netherlands Antillean guilders', 'ANG', 'ANG'],
  AOA: ['קואנזה אנגולי', 'Angolan kwanzas', 'Kz', 'AOA'],
  ARS: ['פסו ארגנטינאי', 'Argentine pesos', '$', 'ARS'],
  AUD: ['דולר אוסטרלי', 'Australian dollars', '$', 'A$'],
  AWG: ['פלורין של ארובה', 'Aruban florin', 'AWG', 'AWG'],
  AZN: ['מאנאט אזרבייג׳ני', 'Azerbaijani manats', '₼', 'AZN'],
  BAM: ['מארק סחיר של בוסניה והרצגובינה', 'Bosnia-Herzegovina convertible marks', 'KM', 'BAM'],
  BBD: ['דולר ברבדיאני', 'Barbadian dollars', '$', 'BBD'],
  BDT: ['טאקה בנגלדשי', 'Bangladeshi takas', '৳', 'BDT'],
  BGN: ['לב בולגרי', 'Bulgarian leva', 'BGN', 'BGN'],
  BHD: ['דינר בחרייני', 'Bahraini dinars', 'BHD', 'BHD'],
  BIF: ['פרנק בורונדי', 'Burundian franc', 'BIF', 'BIF'],
  BMD: ['דולר ברמודה', 'Bermudan dollars', '$', 'BMD'],
  BND: ['דולר ברוניי', 'Brunei dollars', '$', 'BND'],
  BOB: ['בוליביאנו', 'Bolivian bolivianos', 'Bs', 'BOB'],
  BRL: ['ריאל ברזילאי', 'Brazilian reals', 'R$', 'R$'],
  BSD: ['דולר בהאמי', 'Bahamian dollars', '$', 'BSD'],
  BTN: ['נגולטרום בהוטני', 'Bhutanese ngultrums', 'BTN', 'BTN'],
  BWP: ['פולה בוטסואני', 'Botswanan pulas', 'P', 'BWP'],
  BYN: ['רובל בלרוסי', 'Belarusian rubles', 'р', 'BYN'],
  BZD: ['דולר בליזי', 'Belize dollars', '$', 'BZD'],
  CAD: ['דולר קנדי', 'Canadian dollars', '$', 'CA$'],
  CDF: ['פרנק קונגולזי', 'Congolese francs', 'CDF', 'CDF'],
  CHF: ['פרנק שוויצרי', 'Swiss francs', 'CHF', 'CHF'],
  CLP: ['פסו צ׳ילאני', 'Chilean peso', '$', 'CLP'],
  CNY: ['יואן סיני', 'Chinese yuan', '¥', 'CN¥'],
  COP: ['פסו קולומביאני', 'Colombian peso', '$', 'COP'],
  CRC: ['קולון קוסטה־ריקני', 'Costa Rican colóns', '₡', 'CRC'],
  CUC: ['פסו קובני להמרה', 'Cuban convertible pesos', '$', 'CUC'],
  CUP: ['פסו קובני', 'Cuban pesos', '$', 'CUP'],
  CVE: ['אסקודו כף ורדה', 'Cape Verdean escudos', 'CVE', 'CVE'],
  CZK: ['קורונה צ׳כית', 'Czech korunas', 'Kč', 'CZK'],
  DJF: ['פרנק ג׳יבוטי', 'Djiboutian franc', 'DJF', 'DJF'],
  DKK: ['כתר דני', 'Danish kroner', 'kr', 'DKK'],
  DOP: ['פסו דומיניקני', 'Dominican pesos', '$', 'DOP'],
  DZD: ['דינר אלג׳ירי', 'Algerian dinars', 'DZD', 'DZD'],
  EGP: ['לירה מצרית', 'Egyptian pounds', 'E£', 'EGP'],
  ERN: ['נאקפה אריתראי', 'Eritrean nakfas', 'ERN', 'ERN'],
  ETB: ['ביר אתיופי', 'Ethiopian birrs', 'ETB', 'ETB'],
  EUR: ['אירו', 'euros', '€', '€'],
  FJD: ['דולר פיג׳י', 'Fijian dollars', '$', 'FJD'],
  FKP: ['לירה של איי פוקלנד', 'Falkland Islands pounds', '£', 'FKP'],
  GBP: ['לירה שטרלינג', 'British pounds', '£', '£'],
  GEL: ['לארי גאורגי', 'Georgian laris', '₾', 'GEL'],
  GHS: ['סדי גאני', 'Ghanaian cedis', 'GH₵', 'GHS'],
  GIP: ['פאונד גיברלטר', 'Gibraltar pounds', '£', 'GIP'],
  GMD: ['דלסי גמבי', 'Gambian dalasis', 'GMD', 'GMD'],
  GNF: ['פרנק גינאי', 'Guinean franc', 'FG', 'GNF'],
  GTQ: ['קצאל גואטמלי', 'Guatemalan quetzals', 'Q', 'GTQ'],
  GYD: ['דולר גיאני', 'Guyanaese dollars', '$', 'GYD'],
  HKD: ['דולר הונג קונגי', 'Hong Kong dollars', '$', 'HK$'],
  HNL: ['למפירה הונדורי', 'Honduran lempiras', 'L', 'HNL'],
  HRK: ['קונה קרואטי', 'Croatian kunas', 'kn', 'HRK'],
  HTG: ['גורד האיטי', 'Haitian gourdes', 'HTG', 'HTG'],
  HUF: ['פורינט הונגרי', 'Hungarian forint', 'Ft', 'HUF'],
  IDR: ['רופיה אינדונזית', 'Indonesian rupiah', 'Rp', 'IDR'],
  ILS: ['שקלים חדשים', 'Israeli new shekels', '₪', '₪'],
  INR: ['רופי הודי', 'Indian rupees', '₹', '₹'],
  IQD: ['דינר עיראקי', 'Iraqi dinar', 'IQD', 'IQD'],
  IRR: ['ריאל איראני', 'Iranian rial', 'IRR', 'IRR'],
  ISK: ['כתר איסלנדי', 'Icelandic króna', 'kr', 'ISK'],
  JMD: ['דולר ג׳מייקני', 'Jamaican dollars', '$', 'JMD'],
  JOD: ['דינר ירדני', 'Jordanian dinars', 'JOD', 'JOD'],
  JPY: ['ין יפני', 'Japanese yen', '¥', '¥'],
  KES: ['שילינג קנייתי', 'Kenyan shillings', 'KES', 'KES'],
  KGS: ['סום קירגיזי', 'Kyrgyz soms', '⃀', 'KGS'],
  KHR: ['ריל קמבודי', 'Cambodian riels', '៛', 'KHR'],
  KMF: ['פרנק קומורואי', 'Comorian franc', 'CF', 'KMF'],
  KPW: ['וון צפון קוריאני', 'North Korean won', '₩', 'KPW'],
  KRW: ['וון דרום קוריאני', 'South Korean won', '₩', '₩'],
  KWD: ['דינר כוויתי', 'Kuwaiti dinars', 'KWD', 'KWD'],
  KYD: ['דולר קיימני', 'Cayman Islands dollars', '$', 'KYD'],
  KZT: ['טנגה קזחסטני', 'Kazakhstani tenges', '₸', 'KZT'],
  LAK: ['קיפ לאי', 'Laotian kip', '₭', 'LAK'],
  LBP: ['לירה לבנונית', 'Lebanese pound', 'L£', 'LBP'],
  LKR: ['רופי סרי לנקי', 'Sri Lankan rupees', 'Rs', 'LKR'],
  LRD: ['דולר ליברי', 'Liberian dollars', '$', 'LRD'],
  LSL: ['לוטי לסותי', 'Lesotho lotis', 'LSL', 'LSL'],
  LYD: ['דינר לובי', 'Libyan dinars', 'LYD', 'LYD'],
  MAD: ['דירהם מרוקאי', 'Moroccan dirhams', 'MAD', 'MAD'],
  MDL: ['לאו מולדובני', 'Moldovan lei', 'MDL', 'MDL'],
  MGA: ['אריארי מלגשי', 'Malagasy ariary', 'Ar', 'MGA'],
  MKD: ['דינר מקדוני', 'Macedonian denari', 'MKD', 'MKD'],
  MMK: ['קיאט מיאנמרי', 'Myanmar kyat', 'K', 'MMK'],
  MNT: ['טוגרוג מונגולי', 'Mongolian tugriks', '₮', 'MNT'],
  MOP: ['פטקה של מקאו', 'Macanese patacas', 'MOP', 'MOP'],
  MRU: ['אואוגויה מאוריטני', 'Mauritanian ouguiyas', 'MRU', 'MRU'],
  MUR: ['רופי מאוריציני', 'Mauritian rupees', 'Rs', 'MUR'],
  MVR: ['רופיות מלדיביות', 'Maldivian rufiyaas', 'MVR', 'MVR'],
  MWK: ['קואצ׳ה מלאווי', 'Malawian kwachas', 'MWK', 'MWK'],
  MXN: ['פסו מקסיקני', 'Mexican pesos', '$', 'MX$'],
  MYR: ['רינגיט מלזי', 'Malaysian ringgits', 'RM', 'MYR'],
  MZN: ['מטיקל מוזמביני', 'Mozambican meticals', 'MZN', 'MZN'],
  NAD: ['דולר נמיבי', 'Namibian dollars', '$', 'NAD'],
  NGN: ['נאירה ניגרי', 'Nigerian nairas', '₦', 'NGN'],
  NIO: ['קורדובה ניקרגואה', 'Nicaraguan córdobas', 'C$', 'NIO'],
  NOK: ['כתר נורווגי', 'Norwegian kroner', 'kr', 'NOK'],
  NPR: ['רופי נפאלי', 'Nepalese rupees', 'Rs', 'NPR'],
  NZD: ['דולר ניו זילנדי', 'New Zealand dollars', '$', 'NZ$'],
  OMR: ['ריאל עומאני', 'Omani rials', 'OMR', 'OMR'],
  PAB: ['בלבואה פנמי', 'Panamanian balboas', 'PAB', 'PAB'],
  PEN: ['סול פרואני', 'Peruvian soles', 'PEN', 'PEN'],
  PGK: ['קינה של פפואה גינאה החדשה', 'Papua New Guinean kina', 'PGK', 'PGK'],
  PHP: ['פסו פיליפיני', 'Philippine pesos', '₱', 'PHP'],
  PKR: ['רופי פקיסטני', 'Pakistani rupee', 'Rs', 'PKR'],
  PLN: ['זלוטי פולני', 'Polish zlotys', 'zł', 'PLN'],
  PYG: ['גוארני פרגוואי', 'Paraguayan guarani', '₲', 'PYG'],
  QAR: ['ריאל קטארי', 'Qatari riyals', 'QAR', 'QAR'],
  RON: ['לאו רומני', 'Romanian lei', 'lei', 'RON'],
  RSD: ['דינר סרבי', 'Serbian dinars', 'RSD', 'RSD'],
  RUB: ['רובל רוסי', 'Russian rubles', '₽', 'RUB'],
  RWF: ['פרנק רואנדי', 'Rwandan franc', 'RF', 'RWF'],
  SAR: ['ריאל סעודי', 'Saudi riyals', 'SAR', 'SAR'],
  SBD: ['דולר איי שלמה', 'Solomon Islands dollars', '$', 'SBD'],
  SCR: ['רופי סיישלי', 'Seychellois rupees', 'SCR', 'SCR'],
  SDG: ['לירה סודנית', 'Sudanese pounds', 'SDG', 'SDG'],
  SEK: ['כתר שוודי', 'Swedish kronor', 'kr', 'SEK'],
  SGD: ['דולר סינגפורי', 'Singapore dollars', '$', 'SGD'],
  SHP: ['פאונד סנט הלני', 'St. Helena pounds', '£', 'SHP'],
  SLE: ['ליאון סיירה לאוני', 'Sierra Leonean leones', 'SLE', 'SLE'],
  SLL: ['ליאון סיירה לאוני - 1964-2022', 'Sierra Leonean leone (1964—2022)', 'SLL', 'SLL'],
  SOS: ['שילינג סומלי', 'Somali shilling', 'SOS', 'SOS'],
  SRD: ['דולר סורינאמי', 'Surinamese dollars', '$', 'SRD'],
  SSP: ['לירה דרום-סודנית', 'South Sudanese pounds', '£', 'SSP'],
  STN: ['דוברה של סאו טומה ופרינסיפה', 'São Tomé & Príncipe dobras', 'Db', 'STN'],
  SVC: ['קולונים סלבדוריים', 'Salvadoran colones', 'SVC', 'SVC'],
  SYP: ['לירה סורית', 'Syrian pound', '£', 'SYP'],
  SZL: ['לילנגני סווזילנדי', 'Swazi emalangeni', 'SZL', 'SZL'],
  THB: ['בהט תאילנדי', 'Thai baht', '฿', '฿'],
  TJS: ['סומוני טג׳קיסטני', 'Tajikistani somonis', 'TJS', 'TJS'],
  TMT: ['מאנאט טורקמני', 'Turkmenistani manat', 'TMT', 'TMT'],
  TND: ['דינר טוניסאי', 'Tunisian dinars', 'TND', 'TND'],
  TOP: ['פאנגה טונגי', 'Tongan paʻanga', 'T$', 'TOP'],
  TRY: ['לירות טורקיות', 'Turkish Lira', '₺', 'TRY'],
  TTD: ['דולר טרינידדי', 'Trinidad & Tobago dollars', '$', 'TTD'],
  TWD: ['דולר טייוואני חדש', 'New Taiwan dollars', 'NT$', 'NT$'],
  TZS: ['שילינג טנזני', 'Tanzanian shillings', 'TZS', 'TZS'],
  UAH: ['הריבנה אוקראיני', 'Ukrainian hryvnias', '₴', 'UAH'],
  UGX: ['שילינג אוגנדי', 'Ugandan shilling', 'UGX', 'UGX'],
  USD: ['דולר אמריקאי', 'US dollars', '$', '$'],
  UYU: ['פסו אורוגוואי', 'Uruguayan pesos', '$', 'UYU'],
  UZS: ['סום אוזבקי', 'Uzbekistani som', 'UZS', 'UZS'],
  VES: ['בוליבר ונצואלי', 'Venezuelan bolívars', 'VES', 'VES'],
  VND: ['דונג וייטנאמי', 'Vietnamese dong', '₫', '₫'],
  VUV: ['ואטו של ונואטו', 'Vanuatu vatu', 'VUV', 'VUV'],
  WST: ['טאלה סמואי', 'Samoan tala', 'WST', 'WST'],
  XAF: ['פרנק CFA מרכז אפריקני', 'Central African CFA franc', 'FCFA', 'FCFA'],
  XCD: ['דולר מזרח קריבי', 'East Caribbean dollars', '$', 'EC$'],
  XCG: ['גילדר של הקריביים', 'Caribbean guilders', 'Cg.', 'Cg.'],
  XDR: ['זכויות משיכה מיוחדות', 'special drawing rights', 'XDR', 'XDR'],
  XOF: ['פרנק CFA מערב אפריקני', 'West African CFA franc', 'F CFA', 'F CFA'],
  XPF: ['פרנק פולינזיה הצרפתית', 'CFP franc', 'CFPF', 'CFPF'],
  XSU: ['XSU', 'Sucres', 'XSU', 'XSU'],
  YER: ['ריאל תימני', 'Yemeni rial', 'YER', 'YER'],
  ZAR: ['ראנד דרום אפריקאי', 'South African rand', 'R', 'ZAR'],
  ZMW: ['קוואצ׳ה זמבי', 'Zambian kwachas', 'ZK', 'ZMW'],
  ZWG: ['זהב של זימבבואה', 'Zimbabwean gold', 'ZWG', 'ZWG'],
  ZWL: ['ZWL', 'Zimbabwean dollars (2009–2024)', 'ZWL', 'ZWL'],
};
